# Generated by Django 4.0.6 on 2022-07-12 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cipher', models.CharField(max_length=25, verbose_name='Шифр')),
                ('is_in_ISUP', models.BooleanField(help_text='Возможно стоило сделать поле текстовым', verbose_name='Наличие в ИСУП')),
                ('number_DS', models.CharField(max_length=25, verbose_name='Номер ДС')),
                ('DS_date', models.DateField(verbose_name='Дата ДС')),
                ('transit', models.CharField(help_text='Не знаю что это, возможно стоило сделать поле Да/Нет', max_length=30, verbose_name='Транзит')),
                ('about_contract', models.CharField(max_length=255, verbose_name='Предмет договора')),
                ('risks', models.PositiveSmallIntegerField(choices=[(1, 'Какой-то риск 1'), (2, 'Какой-то риск 2'), (3, 'Какой-то риск 3'), (4, 'Какой-то риск 4'), (5, 'Какой-то риск 5'), (6, 'Какой-то риск 6'), (7, 'Какой-то риск 7'), (8, 'Какой-то риск 8'), (9, 'Какой-то риск 9')], verbose_name='risks')),
                ('vat', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Сумма НДС')),
                ('start_date', models.DateField(verbose_name='Дата заключения договора')),
                ('end_date', models.DateField(verbose_name='Срок действия договора')),
                ('work_completion_time', models.DateField(verbose_name='Срок исполнения работ по договору')),
                ('completion_date', models.DateField(verbose_name='Дата завершения работ')),
                ('main_status', models.PositiveSmallIntegerField(choices=[(1, 'status 1'), (2, 'status 2'), (3, 'status 3'), (4, 'status 4'), (5, 'status 5')], verbose_name='main_status')),
                ('money_receipt', models.DateField(verbose_name='Дата поступления денег')),
                ('actual_performance', models.DateField(verbose_name='Дата фактического исполнения')),
                ('risks_signs', models.CharField(max_length=255, verbose_name='Проявление рисков')),
                ('reaction', models.CharField(max_length=255, verbose_name='Меры реагирования при проявлении рисков')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
        migrations.CreateModel(
            name='MonthStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.CharField(max_length=255, verbose_name='Исполнение')),
                ('date', models.DateField(verbose_name='Дата')),
                ('certificate_of_completion', models.BooleanField(default=False, verbose_name='АВР')),
            ],
            options={
                'verbose_name': 'Статус за месяц',
                'verbose_name_plural': 'Статусы за месяц',
            },
        ),
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'ПМ',
                'verbose_name_plural': "ПМ'ы",
            },
        ),
        migrations.CreateModel(
            name='SupplementaryContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование доп. договора')),
                ('data', models.DateField(verbose_name='Доп. договор от:')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.contract', verbose_name='К договору')),
            ],
            options={
                'verbose_name': 'Доп. договор',
                'verbose_name_plural': 'Доп. договоры',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата комментария')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.contract', verbose_name='Договор')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.contractor', verbose_name='Контрагент'),
        ),
    ]
