# Generated by Django 4.0.6 on 2022-07-12 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_alter_status_options_contract_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work.projectmanager', verbose_name='ПМ'),
        ),
    ]
